config/routes.rb
Rails.application.routes.draw do

  root "welcome#index"

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get '/dashboard', to: 'dashboard#index'

  resources :sessions, only: [:create, :destroy]
  resources :welcome, only: [:index]


  resources :ventures do
    resources :terms, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  end

  resources :ventures, only: [:index, :show, :new, :create, :edit, :update, :destroy]


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |a|
      a.provider = auth.provider
      a.uid = auth.uid
      a.name = auth.info.name
      a.oauth_token = auth.credentials.token
      a.oauth_expires_at = Time.at(auth.credentials.expires_at)
      a.user_id = User.create.id if a.user_id == nil
      a.save!
    end
  end

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :ventures
  has_many :users, through: :ventures

  
end

app/models/census.rb
class Census

  attr_reader :raw_values

  def initialize(array)
    @raw_values = array
    # binding.pry
  end


  def date_sorted_sales_array
    monthly_sales = {}
    raw_values.map do |set|
      monthly_sales[set[4]] = set[0].to_i
    end
    # binding.pry
    monthly_sales.keys.sort.map {|key| monthly_sales[key]}
  end

  def percent_of_total_us
    #  11077,000,000  $493.300,000,000 billion
    ((date_sorted_sales_array[23] / 493300.0) * 100).round(2)
  end

end

#
# set: only really need cell value and time!

# # "[[\"cell_value\",\"category_code\",\"data_type_code\",\"seasonally_adj\",\"time\"],\n[\"10833\",\"453\",\"SM\",\"yes\",\"2017-02\"],\n[\"10156\",\"453\",\"SM\",\"yes\",\"2016-01\"],\n[\"10082\",\"453\",\"SM\",\"yes\",\"2016-02\"],\n[\"10278\",\"453\",\"SM\",\"yes\",\"2016-03\"],\n[\"10602\",\"453\",\"SM\",\"yes\",\"2016-04\"],\n[\"10843\",\"453\",\"SM\",\"yes\",\"2017-03\"],\n[\"10895\",\"453\",\"SM\",\"yes\",\"2017-04\"],\n[\"10449\",\"453\",\"SM\",\"yes\",\"2016-05\"],\n[\"10771\",\"453\",\"SM\",\"yes\",\"2017-05\"],\n[\"10502\",\"453\",\"SM\",\"yes\",\"2016-06\"],\n[\"10468\",\"453\",\"SM\",\"yes\",\"2016-07\"],\n[\"10579\",\"453\",\"SM\",\"yes\",\"2017-06\"],\n[\"10830\",\"453\",\"SM\",\"yes\",\"2017-07\"],\n[\"10367\",\"453\",\"SM\",\"yes\",\"2016-08\"],\n[\"10795\",\"453\",\"SM\",\"yes\",\"2017-08\"],\n[\"10684\",\"453\",\"SM\",\"yes\",\"2016-09\"],\n[\"10870\",\"453\",\"SM\",\"yes\",\"2017-09\"],\n[\"10795\",\"453\",\"SM\",\"yes\",\"2016-10\"],\n[\"10944\",\"453\",\"SM\",\"yes\",\"2017-10\"],\n[\"10576\",\"453\",\"SM\",\"yes\",\"2016-11\"],\n[\"10755\",\"453\",\"SM\",\"yes\",\"2017-01\"],\n[\"11368\",\"453\",\"SM\",\"yes\",\"2017-11\"],\n[\"11077\",\"453\",\"SM\",\"yes\",\"2017-12\"],\n[\"10653\",\"453\",\"SM\",\"yes\",\"2016-12\"]]"
#
# [10156, 10082, 10278, 10602, 10449, 10502, 10468, 10367, 10684, 10795, 10576, 10653, 10755, 10833, 10843, 10895, 10771, 10579, 10830, 10795, 10870, 10944, 11368, 11077, 0]

app/models/google_search_weekly.rb
class GoogleSearchWeekly

  attr_reader :standard, :word_1, :word_2, :word_3, :word_4

  def initialize(attrs)
    @week = attrs.values[0]
    @standard = attrs.values[1].to_i
    @word_1 = attrs.values[2].to_i
    @word_2 = attrs.values[3].to_i
    @word_3 = attrs.values[4].to_i
    @word_4 = attrs.values[5].to_i
  end


end

app/models/google_shop_weekly.rb
class GoogleShopWeekly

  attr_reader :standard, :word_1, :word_2, :word_3, :word_4

  def initialize(attrs)
    @week = attrs.values[0]
    @standard = attrs.values[1].to_i
    @word_1 = attrs.values[2].to_i
    @word_2 = attrs.values[3].to_i
    @word_3 = attrs.values[4].to_i
    @word_4 = attrs.values[5].to_i
  end


end

app/models/snapshot.rb
class Snapshot < ApplicationRecord
  belongs_to :venture
end

app/models/term.rb
class Term < ApplicationRecord
  validates :words, presence: true
  serialize :words, Array


  belongs_to :venture
  belongs_to :snapshot
  has_one :user, through: :venture

end

app/models/user.rb
class User < ApplicationRecord

  has_one :authentication
  has_many :ventures



end

app/models/venture.rb
class Venture < ApplicationRecord
  validates :title, :description, presence: true

  belongs_to :user
  belongs_to :category
  has_many :terms
  has_many :snapshots
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
    # binding.pry
  end



end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
    @ventures = current_user.ventures.all
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


  def create
    user = Authentication.from_omniauth(request.env["omniauth.auth"]).user
    # binding.pry
    session[:user_id] = user.id
    redirect_to dashboard_path
  end

  def destroy
    session.destroy
    redirect_to root_path
  end


end

app/controllers/terms_controller.rb
class TermsController < ApplicationController

  def index
    @venture = Venture.find(params[:venture_id])
    @terms = @venture.terms
  end

  def new
    @venture = current_user.ventures.last
    @term = @venture.terms.new

  end

  def create
    @venture = current_user.ventures.last
    snapshot = Snapshot.create(venture_id: @venture.id)

    @term = @venture.terms.new(term_params)
    @term.update(venture_id: @venture.id, snapshot_id: snapshot.id)
    # binding.pry
    if @term.save
      redirect_to venture_path(@venture)
    else
      flash[:notice] = "Please try again"
      redirect_to new_term_path
    end

  end

  def edit
    @venture = current_user.ventures.find(params[:venture_id])
    @terms = @venture.terms.find(params[:id])
  end

  def update
    @venture = Venture.find(params[:venture_id])
    terms = @venture.terms.find(params[:id])
    terms.update(term_params)
    redirect_to ventures_path
  end

  private
    def term_params
      params.require(:term).permit(:words => [])
    end

end

app/controllers/ventures_controller.rb
class VenturesController < ApplicationController

  def index
    @ventures = current_user.ventures.all
  end


  def show
    @venture = Venture.where(user_id: current_user.id).find(params[:id])
    @terms = Term.where(venture_id: @venture.id).last
    @industry = Category.find(@venture.category_id)
    @hu_insight = HuInsights.insight_maker(@terms.words, @industry.code)


  end


  def new
    @venture = Venture.new
    @categories = Category.all
  end

  def create
    @venture = current_user.ventures.new(venture_params)
    if @venture.save
      redirect_to new_venture_term_path(@venture)
    else
      render :new
    end
  end


  def edit
    @venture = current_user.ventures.find(params[:id])
    @categories = Category.all
  end


  def update
    @venture = current_user.ventures.find(params[:id])
    @venture.update(venture_params)
    redirect_to venture_path(@venture)
  end

  private

    def venture_params
      params.require(:venture).permit(:title, :description, :notes, :category_id)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index


  end



end


#
# <button class="widget-actions-item export"
# title="CSV"
# ng-if="isEditor || (export &amp;&amp; showActionButton())"
#   ng-click="export()"
#   track="['Widget', type, 'Export']"
#   ve-tracking=""
#   jslog="39388; track:generic_click">
#
#
#     <i class="material-icons-extended gray">file_download</i>
#
#   </button>

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/index.html.erb
<h3 class="color-teal" id="size-1dot5-em">Hi, <%=current_user.authentication.name%>!</h3>

<h3 id="text-bold"><%= link_to "Start a New Venture", new_venture_path %></h3><br><br>

<% @ventures.each do |venture| %>
Title: <%= link_to "#{venture.title}", venture_path(venture) %><br>
<% end  %>

app/views/layouts/_footer.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
  <p class="color-teal" id="center-text">Lauren Billington 2018 </p>
  <p class="color-teal" id="center-text"> <%= image_tag "hu-owl-wh-backgroud.jpg", size: "30x30"  %></p>

app/views/layouts/_nav_bar.html.erb
      <nav class="navbar">
        <div class="container">
          <div class="navbar-brand">
            <a class="navbar-item"  >
              <!-- <img src="https://bulma.io/images/bulma-type-white.png" alt="Logo"> -->
              <%= image_tag "teal-hu.jpg", size: "30x30"  %>
            </a>
            <span class="navbar-burger burger" data-target="navbarMenuHeroA">
              <span></span>
              <span></span>
              <span></span>
            </span>
          </div>
          <div id="navbarMenuHeroA" class="navbar-menu">
            <div class="navbar-end">
              <a class="navbar-item">
                <%= link_to "Home", root_path %>
              </a>
              <a class="navbar-item">
                <% if current_user %>
                <%= link_to "You-Hu", dashboard_path %>
                <% else %>
                <% end %>
              </a>
              <a class="navbar-item">
                <% if current_user %>
                <%= link_to "Signed in as #{current_user.authentication.name}", dashboard_path %>

                <% else %>
                <% end %>
              </a>
              <a class="navbar-item">
                <% if current_user %>
                <%= link_to "Sign out", signout_path, id: "sign_out" %>
                <% else %>
                <%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %>
                <% end %>
              </a>
              <div class=""><% flash.each do |key, value| %>
                 <div class="alert alert-<%= key %>"><%= value %>
               <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hu</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag  "https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.css" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.css"> -->


  </head>
  <body>
    <section class="hero is-primary is-medium">
      <!-- Hero head: will stick at the top -->
      <div class="hero-head">
      <%= render 'layouts/nav_bar' %>
      </div>
    </section>

    <div class="container">
      <div class="level columns">
        <div class="level-left column">
          <div class="level-item">
            <div class="container">

                  <%= yield %>

            </div>
          </div>
        </div>
      </div>
    </div>





      <!-- Hero footer: will stick at the bottom -->
      <div class="hero-foot">
        <nav class="tabs">
          <div class="container">
            <%= render 'layouts/footer' %>
            <!-- <ul>
              <li class="is-active"><a>Overview</a></li>
              <li><a>Modifiers</a></li>
              <li><a>Grid</a></li>
              <li><a>Elements</a></li>
              <li><a>Components</a></li>
              <li><a>Layout</a></li>
            </ul> -->
          </div>
        </nav>
      </div>
     </section>

  </body>
</html>

app/views/terms/edit.html.erb
<h2>Update Search terms for <%= @venture.title %>  </h2>

<p>Here are your notes: </p><br>
<p><%= @venture.notes%></p><br>

<%= form_for [@venture, @terms] do |f|  %>
<p>Add up to 4 search terms</p>
<%= f.text_field('words', multiple: true) %>
<%= f.text_field('words', multiple: true) %>
<%= f.text_field('words', multiple: true) %>
<%= f.text_field('words', multiple: true) %>

<%= f.submit "Get Report", venture_id: @venture.id %>
<% end  %>



<!-- If you use nested resources,
   <%= text_field_tag 'user[firstname]' %>
in your form, will result in
   params[:user][:firstname] -->

app/views/terms/index.html.erb
<h2>Terms for <%= @venture.title %></h2>

<% @terms.each do |collection| %>
<%= collection.words %><br>
<% end  %>

app/views/terms/new.html.erb
<h3 id="size-1dot5-em">Create Search terms for <%= @venture.title %>  </h3>

<p>Here are your notes: </p><br>
<p><%= @venture.notes%></p><br>

<%= form_for [@venture, @term] do |f|  %>
<p>Add up to 4 search terms or phrases</p>
<%= f.text_field('words', multiple: true) %>
<%= f.text_field('words', multiple: true) %>
<%= f.text_field('words', multiple: true) %>
<%= f.text_field('words', multiple: true) %>

<%= f.submit "Get Report", venture_id: @venture.id %>
<% end  %>



<!-- If you use nested resources,
   <%= text_field_tag 'user[firstname]' %>
in your form, will result in
   params[:user][:firstname] -->

app/views/ventures/edit.html.erb
<h3 class="color-teal" id="size-1dot5-em">Edit <%= @venture.title %></h3>
<br>

<%= form_for @venture do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<%= f.label :description %>
<%= f.text_field :description %>
<br><br>
<h3>Select your Industry</h3>
<%= f.select(:category_id, @categories.map {|c| [c.title, c.id]}) %>
<br>
<br>
<br>
<%= f.label :notes %><br>
<%= f.text_area :notes %><br>
<%= f.submit %>

<% end  %>

app/views/ventures/index.html.erb
<h3 class="color-teal" id="size-1dot5-em">My Ventures</h3>

<h3 id="text-bold"><%= link_to "Start a New Venture", new_venture_path %></h3><br><br>

<% @ventures.each do |venture| %>
Title: <%= link_to "  #{venture.title}", venture_path(venture) %><br>
<% end  %>

app/views/ventures/new.html.erb
<h3 class="color-teal" id="size-1dot5-em">New Venture </h3>
<br>

<%= form_for @venture do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<%= f.label :description %>
<%= f.text_field :description %>
<br><br>
<h3>Select your Industry</h3>

<%= f.select(:category_id, @categories.map {|c| [c.title, c.id]}) %>
<br>
<br>
<br>


<p class="color-teal" id="text-bold">Consider these questions before choosing your search terms on the following page.</p><br>
  <p >
    <ul class="color-teal">
      <li>What problems does your Venture solve?
      <li>What makes your Venture different or better than other Ventures?
      <li>What groups of people do you think would be interested in your Venture? Think of factors such as age, gender, location, and financial capacity.
      <li>What are some similar companies or products? How would you search for these products online? What terms would you use?
    </ul>
  </p>

<br>
<%= f.label :notes %><br>
<%= f.text_area :notes %><br>
<%= f.submit "Next" %>

<% end  %>

app/views/ventures/show.html.erb
<% term_1 = @terms.words[0]%><% term_2 = @terms.words[1]%><% term_3 = @terms.words[2]%><% term_4 = @terms.words[3]%>

<h2 id="size-2-em">Venture: <%= @venture.title%></h2>

<h3 class="color-teal" id="size-1dot5-em">Current Search Terms:</h3>
<h5>"<%= term_1 %>", "<%= term_2 %>", "<%= term_3 %>", "<%= term_4 %>"</h5>
<p id="text-lighter">Terms last updated on <%= @venture.terms.first.updated_at %></p>
<%= link_to "Edit #{@venture.title}", edit_venture_path(@venture) %> || <%= link_to "Edit Search Terms", edit_venture_term_path(@venture, @terms) %><br><br><br><br>
<h3 class="color-teal" id="size-1dot5-em">Hu Interest Scores</h3>

<p class="color-blue" id="text-bold">0-20: Low Interest </p>
<p id="text-lighter">(this range may be acceptable when considering other variables)</p>
<p class="color-green" id="text-bold">20-40: Some Interest</p>
<p class="color-orange" id="text-bold">40-60: Medium Interest</p>
<p class="color-red" id="text-bold">60 + HOT!</p>
<br>



  <div class="columns">

    <div class="column">
      <p class="color-teal" id="text-bold">Google Shop Engine Popularity</p>
      <p>1:  <%= term_1 %>: <%= @hu_insight.google_shop.word_1_insight %></p>
      <p>2:  <%= term_2 %>: <%= @hu_insight.google_shop.word_2_insight %></p>
      <p>3:  <%= term_3 %>: <%= @hu_insight.google_shop.word_3_insight %></p>
      <p>4:  <%= term_4 %>: <%= @hu_insight.google_shop.word_4_insight %></p>
    </div>

    <div class="column">
      <p class="color-teal" id="text-bold">Google Search Engine Popularity</p>
      <p>1:  <%= term_1 %>: <%= @hu_insight.google_search.word_1_insight %></p>
      <p>2:  <%= term_2 %>: <%= @hu_insight.google_search.word_2_insight %></p>
      <p>3:  <%= term_3 %>: <%= @hu_insight.google_search.word_3_insight %></p>
      <p>4:  <%= term_4 %>: <%= @hu_insight.google_search.word_4_insight %></p>
    </div>

  </div>
  <div class="columns">
    <div class="column">
      <canvas id="googleShopChart" width="50" height="20"></canvas>
    </div>
    <div class="column">
      <canvas id="googleSearchChart" width="50" height="20"></canvas>
    </div>
  </div>

  <p id="text-lighter">All data gathered from https://trends.google.com/trends/explore</p><br>

  <p>If you score was less than 20 and your industry is not growing (or the industry is a comparatively small one), your Venture may not be financially successful. However, many Americans are successful in niche markets. Continue your research into regions of interest (local brick and mortor versus e-commerce), and the price per item or service which would be enticing to a small customer base</p><br><br>

<div>
<h2 class="color-teal" id="size-1dot5-em">Census Trends  - Overall US, Industry specific</h2><br>

<h3 id="text-bold">US Market Insight for "<%= @industry.title %>"</h3>
<p class="color-teal" id="text-bold">Your industry accounts for <%=  @hu_insight.census.percent_of_total_us%> % of the total US Retail and Food Service</p><br>


<h3 id="center-text">Industry Performance: Sales in Millions for (2016-2017)</h3>
</div>
<canvas id="myChart" width="100" height="20"></canvas>
<br>
<p id="text-lighter">*All data is gathered from the US MARTS API. See FAQs for more information.
</p>














<script>
var ctx = document.getElementById("myChart");
var data = <%= @hu_insight.census.date_sorted_sales_array %>;
var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: ["JAN16","FEB16","MAR16","APR16","MAY16","JUN16","JUL16","AUG16","SEP16","OCT16","NOV16","DEC16","JAN17","FEB17","MAR17","APR17","MAY17","JUN17","JUL17","AUG17","SEP17","OCT17","NOV17","DEC17"],
        datasets: [{
            label: 'SALES IN MILLIONS',
            data: data,
            backgroundColor: [
                'rgba(54, 162, 235, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(25,	169,	25, 0.2)',
                'rgba(25,	169,	25, 0.2)',
                'rgba(25,	169,	25, 0.2)',
                'rgba(25,	169,	25, 0.2)',
                'rgba(25,	169,	25, 0.2)',
                'rgba(25,	169,	25, 0.2)',
                'rgba(25,	169,	25, 0.2)',
                'rgba(25,	169,	25, 0.2)',
                'rgba(25,	169,	25, 0.2)',
                'rgba(25,	169,	25, 0.2)',
                'rgba(25,	169,	25, 0.2)',
                'rgba(25,	169,	25, 0.2)',
                ],
            borderColor: [
                'rgba(54, 162, 235, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(25,	169,	25, 1)',
                'rgba(25,	169,	25, 1)',
                'rgba(25,	169,	25, 1)',
                'rgba(25,	169,	25, 1)',
                'rgba(25,	169,	25, 1)',
                'rgba(25,	169,	25, 1)',
                'rgba(25,	169,	25, 1)',
                'rgba(25,	169,	25, 1)',
                'rgba(25,	169,	25, 1)',
                'rgba(25,	169,	25, 1)',
                'rgba(25,	169,	25, 1)',
                'rgba(25,	169,	25, 1)'
            ],
            borderWidth: 3
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});
</script>
<script>
var ctx = document.getElementById("googleShopChart");
var data = <%= @hu_insight.google_shop.shop_chart_data %>;
// var googlelabel = <%= @terms.words %>;
var googleShopChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: [1,2,3,4],
        datasets: [{
            label: 'Hu Popularity Score - Out of 100',
            data:  data,
            backgroundColor: [
                'rgba(143,	218,	209, 0.2)',
                'rgba(143,	218,	209, 0.2)',
                'rgba(143,	218,	209, 0.2)',
                'rgba(143,	218,	209, 0.2)'
                ],
            borderColor: [
                'rgba(143,	218,	209, 1)',
                'rgba(143,	218,	209, 1)',
                'rgba(143,	218,	209, 1)',
                'rgba(143,	218,	209, 1)'
                ],
            borderWidth: 3
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});
</script>
<script>

var ctx = document.getElementById("googleSearchChart");
var data = <%= @hu_insight.google_search.search_chart_data %>;
// var googlelabel = <%= @terms.words %>;
var googleSearchChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: [1,2,3,4],
        datasets: [{
            label: 'Hu Popularity Score - Out of 100',
            data:  data,
            backgroundColor: [
                'rgba(143,	218,	209, 0.2)',
                'rgba(143,	218,	209, 0.2)',
                'rgba(143,	218,	209, 0.2)',
                'rgba(143,	218,	209, 0.2)'
                ],
            borderColor: [
                'rgba(143,	218,	209, 1)',
                'rgba(143,	218,	209, 1)',
                'rgba(143,	218,	209, 1)',
                'rgba(143,	218,	209, 1)'
                ],
            borderWidth: 3
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    }
});
</script>

app/views/welcome/index.html.erb
   <!-- Hero content: will be in the middle -->
   <!--<div class="hero-body">
     <div class="container has-text-centered">--->
       <h1 class="title" id="center-text">
         Hu
       </h1>
       <h1 class="title" id="center-text">
         <%= image_tag "hu-owl-wh-backgroud.jpg", size: "200x200" %>
       </h1><br>
       <h2 class="subtitle" id="center-text">
        Who is Hu?
         <p>Hu is an app designed for Entrepreneurs in the initial stages of product development, created by Lauren Billington. Hu aims to help to-be-business owners gain insight into whether or not their ideas could be financially successful by providing data from the US Census and Google Trends</p>

       </h2>
     <!--</div>
   </div>-->